// This file is generated by Slice Machine. Update with care!

import ArticleSlice from './ArticleSlice';
import PopupComponent from './PopupComponent';
import TitleElement from './TitleElement';

export {
	ArticleSlice,
	PopupComponent,
	TitleElement,
};

export const components = {
	article_slice: ArticleSlice,
	popup_component: PopupComponent,
	title_element: TitleElement,
};
