// This file is generated by Slice Machine. Update with care!

import ArticleSlice from './ArticleSlice';
import HeadingElement from './HeadingElement';
import TableSlice from './TableSlice';

export {
	ArticleSlice,
	HeadingElement,
	TableSlice,
};

export const components = {
	article_slice: ArticleSlice,
	heading_element: HeadingElement,
	table_slice: TableSlice,
};
