// This file is generated by Slice Machine. Update with care!

import ChapterSection from './ChapterSection';
import HeadingElement from './HeadingElement';
import TableSlice from './TableSlice';

export {
	ChapterSection,
	HeadingElement,
	TableSlice,
};

export const components = {
	chapter_section: ChapterSection,
	heading_element: HeadingElement,
	table_slice: TableSlice,
};
